openapi: '3.0.0'
info:
  version: 1.0.0
  title: Course management system
  description: This is the api server for a course management system
  contact:
    name: Dan Wang
    email: wnv-crimina@hotmail.com
servers:
  - url: /v1

tags:
  - name: 'users'
    description: 'Operations about users'
  - name: 'auth'
    description: 'User authentication'
  - name: 'courses'
    description: 'Operations about courses'

paths:
  /users:
    post:
      tags:
        - 'users'
      summary: 'Register a new user'
      description: ''
      operationId: 'addUser'
      requestBody:
        description: 'Required user fields'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        400:
          description: 'Bad Request'
        201:
          description: 'Created'

  /users/me:
    get:
      tags:
        - 'users'
      summary: 'Get current user info'
      description: ''
      operationId: 'getUser'
      responses:
        400:
          description: 'Bad Request'
        401:
          description: 'UnAuthorized'
      security:
        - Bearer: []

  /auth:
    post:
      tags:
        - 'auth'
      summary: 'login user'
      operationId: 'login'
      requestBody:
        description: 'Required user fields'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auth'
      responses:
        200:
          description: 'successful'
        400:
          description: 'Invalid username or password'
# --------------------------------- course start -------------------------- #
  /courses:
    get:
      tags:
        - 'courses'
      summary: 'Get all courses'
      description: 'return 10 by default'
      operationId: 'getCourses'
      parameters:
        - name: 'page'
          in: 'query'
          description: 'Current page number'
          schema:
            type: string
        - name: 'pageSize'
          in: 'query'
          description: 'Number of items on each page'
          schema:
            type: number
        - name: 'sort'
          in: 'query'
          description: 'how to sort the result'
          schema:
            type: string
        - name: 'q'
          in: 'query'
          description: 'search key'
          schema:
            type: string
      responses:
        200:
          description: 'successful'
        401:
          description: 'UnAuthorized'
      security:
        - Bearer: []

    post:
      tags:
        - 'courses'
      summary: 'Add new course'
      operationId: 'addCourse'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
      responses:
        200:
          description: 'created'
        400:
          description: 'Bad Request'
        401:
          description: 'UnAuthorized'
      security:
        - Bearer: []

  /courses/{courseId}:
    get:
      tags:
        - 'courses'
      summary: 'Find course by ID'
      description: 'Returns a single course'
      operationId: 'getCourseById'
      parameters:
        - name: 'courseId'
          in: 'path'
          description: 'ID of course to return'
          required: true
          schema:
            type: string
      responses:
        200:
          description: 'Success'
        400:
          description: 'Invalid params'
        401:
          description: 'UnAuthorized'
        404:
          description: 'Course not found'
      security:
        - Bearer: []
    put:
      tags:
        - 'courses'
      summary: 'Updates a course'
      description: ''
      operationId: 'updateCourse'
      parameters:
        - name: 'courseId'
          in: 'path'
          description: 'ID of course to return'
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
      responses:
        200:
          description: 'Success'
        400:
          description: 'Invalid params'
        401:
          description: 'UnAuthorized'
        404:
          description: 'Course not found'
      security:
        - Bearer: []
    delete:
      tags:
        - 'courses'
      summary: 'Deletes a course'
      description: ''
      operationId: 'deleteCourse'
      parameters:
        - name: 'courseId'
          in: 'path'
          description: 'ID of course to return'
          required: true
          schema:
            type: string
      responses:
        200:
          description: 'Success'
        400:
          description: 'Invalid params'
        401:
          description: 'UnAuthorized'
        404:
          description: 'Course not found'
      security:
        - Bearer: []

components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: 'object'
      properties:
        email:
          type: 'string'
        password:
          type: 'string'
        name:
          type: 'string'
          description: 'display name'
    Student:
      type: 'object'
      properties:
        firstName:
          type: 'string'
        lastName:
          type: 'string'
        emailName:
          type: 'string'
    Teacher:
      type: 'object'
      properties:
        firstName:
          type: 'string'
        lastName:
          type: 'string'
        emailName:
          type: 'string'
    Course:
      type: 'object'
      properties:
        code:
          type: 'string'
        name:
          type: 'string'
        description:
          type: 'string'
    Auth:
      type: 'object'
      properties:
        email:
          type: 'string'
        password:
          type: 'string'
