name: Terraform Plan

on:
  push

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: abcde090/leaveList
          event-type: my-event

          