name: Terraform Plan

permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: 'write'

on:
  push

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: my-event
